server:
  port: 8080

spring:
  application:
    name: mini-im
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mini_im?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "CHANGE_ME"
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    com.miniim: info
    org.mybatis: debug
    org.apache.ibatis: debug
    com.baomidou.mybatisplus: debug
    com.miniim.domain.mapper: debug

im:
  caffeine:
    client-msg-id:
      initial-capacity: 100
      maximum-size: 1000
      expire-after-access-seconds: 600
  cron:
    resend:
      enabled: false
      fixed-delay-ms: 60000
  auth:
    issuer: mini-im
    jwt-secret: "CHANGE_ME_PLEASE_CHANGE_ME_PLEASE_CHANGE_ME"
    access-token-ttl-seconds: 1800
    refresh-token-ttl-seconds: 2592000
  service:
    base-url: http://127.0.0.1:${server.port}
  gateway:
    ws:
      host: 0.0.0.0
      port: 9001
      path: /ws
    auth-verify-url: http://127.0.0.1:8080/auth/verify
    push-url: http://127.0.0.1:9001/push
  message:
    ack-timeout-ms: 5000
    max-retry: 3

  code:
    friend-code-length: 8
    group-code-length: 8
    reset-cooldown-seconds: 86400
